### ISSUE TITLE
code show in one line

### ISSUE THREAD

**Issue by Dishant624** [Softwee/codeview-android#21]
CodeView codeView = (CodeView) findViewById(R.id.code_view);

        codeView.setVerticalFadingEdgeEnabled(true);
        codeView.highlightCode("java")
                .setColorTheme(ColorTheme.SOLARIZED_LIGHT)
                .setCodeContent(getString(R.string.code));

**Comment by kbiakov** [comment]
Does your code contains line break characters?

**Comment by Dishant624** [comment]
No

Does your code contains line break characters?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Softwee/codeview-android/issues/21#issuecomment-247554110>,
or mute the thread

**Comment by kbiakov** [comment]
You must add them, because text parser cannot understand where he should slice content on lines.
