### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by alorma** [Softwee/codeview-android#6]
Hi.

Is there any plan to support **markdown**?

**Comment by kbiakov** [comment]
Hi! Any text with line delimiter ("\n") also available to display. Or you want to support highlighting? I didn't find enough examples of its usage, only Github use case, but it only works to take a ficus on code snippets.

**Comment by alorma** [comment]
That's why i want to use it, also for showing readmes as markdown.

At gitskarios, i should let users see .md files in both ways.

**Comment by kbiakov** [comment]
Implemented in [1.1.0](https://github.com/Softwee/codeview-android/releases/tag/1.1.0).
