### ISSUE TITLE
Listener should return line text

### ISSUE THREAD

**Issue by alorma** [Softwee/codeview-android#7]
For example:

 ```
codeView.setCodeListener(new OnCodeLineClickListener() {
      @Override public void onCodeLineClicked(int n, String line) {
       // your logic here 
    }
});
 ```

That's because if we only get the `position`, we should split lines in a different, and maybe we don't do equals than the library does

**Comment by kbiakov** [comment]
Very precise remark, thank you! I will add this in next version and let you know here.
