### ISSUE TITLE
Customize adapter

### ISSUE THREAD

**Issue by alorma** [Softwee/codeview-android#8]
It will be really great if we can set something depending on lines.

For example: at Gitskarios i'm gonna use this lib to show content, and commits diff, so sometimes i need to add comments in a line

**Comment by kbiakov** [comment]
Implemented in [1.1.0](https://github.com/Softwee/codeview-android/releases/tag/1.1.0).

**Comment by alorma** [comment]
Great!

Please, update README with adapter customization 🎉

**Comment by kbiakov** [comment]
Updated. I also added a Github diff (custom adapter) as nice use case in library, so you can see usage in README and how it looks in screenshots.

**Comment by alorma** [comment]
:tada: great!
